<?php include("header.php"); ?>
      <div  class="inner-container">
        <div  class="submenu hidden-xs">
          <div  class="container"><a  href="logo-design.html">Branding / Logo
              Design</a> <a  href="brand-naming.html">Brand Naming</a> <a  href="explainer-videos.html"

               class="menuon">Videos &amp; Animations</a></div>
        </div>
        <div  class="exp-video-doded-bg">
          <div  class="container">
            <div  class="row">
              <h1>Explainer Videos</h1>
            </div>
            <div  class="row">
              <div  class="col-sm-6">
                <div  class="font-29"> Brochures and PowerPoint are passé.
                  Welcome to the new age communication.</div>
                <br>
                <div  class="text-pad-0">With the extraordinary volume of
                  content being generated online every minute, there is a dire
                  need to differentiate and stand out when it comes to conveying
                  a message. Explainer videos serve as the best way to
                  distinguish your brand from the routine content generated by
                  your competition. An explainer or whiteboard video delivers a
                  message in a simple audio visual format, thereby facilitating
                  you to reach out to target audience in a much more effective
                  and focused manner.<br>
                  <br>
                  <br>
                  <a  href="general-enquiries.html"  class="get-started">Get
                    Started</a> <a  href="multimedia-portfolio.html"  class="view-casestudy">View
                    Portfolio</a></div>
              </div>
              <div  class="col-sm-6 margin-bot-0"><img  src="images/explainer-video-company.jpg"

                   alt="Explainer video company from India"  class="img-responsive"

                   height="458"  width="573"></div>
            </div>
          </div>
        </div>
        <div  class="exp-video-how-help">
          <div  class="container">
            <div  class="row">
              <div  class="col-md-12"> <img  src="images/explainer-video-production.jpg"

                   alt="Explainer video production services"  class="img-responsive center-block"

                   height="294"  width="840"> </div>
            </div>
          </div>
        </div>
        <div  class="exp-vid-recent-works-outer">
          <div  class="container">
            <div  class="row">
              <h1>Some of our recent works</h1>
              <br>
            </div>
            <div  class="row">
              <div  class="col-sm-4 no-padding-margin"><a  href="multimedia-portfolio.html"><img

                     src="images/explainer-video1.jpg"  alt=""  class="img-responsive"

                     height="223"  width="396"></a></div>
              <div  class="col-sm-4 no-padding-margin"><a  href="multimedia-portfolio.html"><img

                     src="images/explainer-video2.jpg"  alt=""  class="img-responsive"

                     height="223"  width="396"></a></div>
              <div  class="col-sm-4 no-padding-margin"><a  href="multimedia-portfolio.html"><img

                     src="images/explainer-video3.jpg"  alt=""  class="img-responsive"

                     height="223"  width="396"></a></div>
              <div  class="col-sm-4 no-padding-margin"><a  href="multimedia-portfolio.html">
                  <img  src="images/explainer-video4.jpg"  alt=""  class="img-responsive"

                     height="223"  width="396"></a></div>
              <div  class="col-sm-4 no-padding-margin"><a  href="multimedia-portfolio.html">
                  <img  src="images/explainer-video5.jpg"  alt=""  class="img-responsive"

                     height="223"  width="396"></a></div>
              <div  class="col-sm-4 no-padding-margin"><a  href="multimedia-portfolio.html">
                  <img  src="images/explainer-video6.jpg"  alt=""  class="img-responsive"

                     height="223"  width="396"></a></div>
              <p>&nbsp;</p>
              <div  align="center"> <a  href="multimedia-portfolio.html"  class="view-casestudy">View
                  explainer demo portfolio</a></div>
            </div>
          </div>
        </div>
        <div  class="exp-video-team">
          <div  class="container">
            <div  class="row">
              <div  class="col-sm-7"> <span  class="exp-text">Explainer demos
                  are usually short videos that can be used to describe
                  products, services or businesses in a dynamic yet simplified
                  way of storytelling. Explainer videos can captivate your
                  target audience by sharing the information you want to convey
                  in an innovative way.</span><br>
                <br>
                At Niyati, can help you create engaging explainer videos that
                give you the edge over your competitors. Our expertise in
                scripting, storyboarding, animation, voiceover recording and
                music integration can be put to best use for developing
                explainer videos that meet your requirements. </div>
              <div  class="col-sm-5">
                <h3>Our Team Includes</h3>
                <div  class="exp-video-team-bull">Experienced scriptwriters</div>
                <div  class="exp-video-team-bull">Voiceover artists (any accent)</div>
                <div  class="exp-video-team-bull">Email marketing</div>
                <div  class="exp-video-team-bull">Creative animators</div>
                <div  class="exp-video-team-bull">Post-production team</div>
              </div>
            </div>
          </div>
        </div>
        <div  class="exp-video-making-process">
          <div  class="container">
            <div  class="row">
              <div  class="col-sm-12 margin-bot-0"> <img  src="images/video-making-process.jpg"

                   alt="Whiteboard Animation &amp; Video Scribing"  class="img-responsive"

                   height="712"  width="1090"> </div>
            </div>
          </div>
        </div>
        <div  class="exp-video-types">
          <div  class="container">
            <div  class="row">
              <h1>Types of Explainer videos</h1>
              <br>
            </div>
            <div  class="row">
              <div  class="col-sm-4">
                <div  class="exp-video-team-bull">2D Animated videos</div>
                <div  class="exp-video-team-bull"><a href="http://www.3dlabz.com/" target="_blank">3D animated videos</a></div>
                <div  class="exp-video-team-bull">Whiteboard / Video scribe
                  movies</div>
              </div>
              <div  class="col-sm-4">
                <div  class="exp-video-team-bull">Live action videos</div>
                <div  class="exp-video-team-bull">Typographic videos</div>
                <div  class="exp-video-team-bull">Screencast videos</div>
              </div>
              <div  class="col-sm-4">
                <div  class="exp-video-team-bull">StopMotion animation</div>
                <div  class="exp-video-team-bull">Testimonial videos</div>
                <div  class="exp-video-team-bull">Corporate movies</div>
              </div>
            </div>
          </div>
        </div>
        <div  class="mob-enterprise-sec">
          <div  class="container">
            <div  class="row">
              <h1>More Resources from our Blog on E-Commerce and Mobile</h1>
            </div>
            <div  class="row">
              <div  class="col-sm-4">
                <div  class="mobility-sec"><img  src="images/mobility-1.jpg"  alt=""

                     class="img-responsive"  height="196"  width="340">
                  <div  class="mobility-col">
                    <p>SNAP On-the-Go Voice Transcriptions</p>
                    <a  href="#"  class="btn btn-primary btn-group-lg">View Case
                      Study</a></div>
                </div>
              </div>
              <div  class="col-sm-4">
                <div  class="mobility-sec"><img  src="images/mobility-2.jpg"  alt=""

                     class="img-responsive"  height="196"  width="340">
                  <div  class="mobility-col">
                    <p>Auspicious Days Calendar and Store Locator </p>
                    <a  href="#"  class="btn btn-primary btn-group-lg">View
                      Video</a></div>
                </div>
              </div>
              <div  class="col-sm-4">
                <div  class="mobility-sec"><img  src="images/mobility-3.jpg"  alt=""

                     class="img-responsive"  height="196"  width="340">
                  <div  class="mobility-col">
                    <p>Mobile App UI Design </p>
                    <a  href="#"  class="btn btn-primary btn-group-lg">Read Blog
                      Article</a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
 <?php include("footer.php"); ?>